parser: babel-eslint
extends: airbnb
env:
  browser: true
  mocha: true
plugins:
  - react
  - jsx-a11y
  - import
settings:
  import/core-modules:
    - electron
  import/resolver: webpack 
rules:
  react/sort-comp:
    - error
    - order:
      - 'type-annotations'
      - 'static-methods'
      - 'lifecycle'
      - '/^on.+$/'
      - '/^(get|set)(?!(InitialState$|DefaultProps$|ChildContext$)).+$/'
      - 'everything-else'
      - '/^render.+$/'
      - 'render'
