parser: babel-eslint
extends:
  - airbnb
  - plugin:flowtype/recommended
env:
  browser: true
  mocha: true
plugins:
  - react
  - jsx-a11y
  - import
  - flowtype
settings:
  import/core-modules:
    - electron
  import/resolver: webpack
  flowtype:
    onlyFilesWithFlowAnnotation: true
rules:
  class-methods-use-this:
    - off
  react/sort-comp:
    - error
    - order:
      - 'type-annotations'
      - 'static-methods'
      - 'lifecycle'
      - '/^on.+$/'
      - '/^(get|set)(?!(InitialState$|DefaultProps$|ChildContext$)).+$/'
      - 'everything-else'
      - '/^render.+$/'
      - 'render'
